apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-daemonset
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: multitool
  template:
    metadata:
      labels:
        name: multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        ports:
        - containerPort: 8080
        env: 
          - name: HTTP_PORT
            value: "1189"
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/
