apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
spec:
  selector:
    app: webapp
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: 80
    - name: multitool
      port: 8080
      protocol: TCP
      targetPort: 1180
