apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-deployment
  labels:
    app: multitool
spec:
  replicas: {{ .Values.app2.replicas }}
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: {{ .Values.app2.image.name }}
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "8080"
